---

- name: create registry configuration directory
  file:
    path: "{{ registry_config_dir }}"
    state: directory
    owner: root
    group: "{{ registry_system_group }}"
    mode: 0775

- name: create config.yml
  template:
    src: "registry/config.yml.j2"
    dest: "{{ registry_config_dir }}/config.yml"
    force: true
    owner: root
    group: "{{ registry_system_group }}"
    mode: 0664
  notify:
    - validate config
    - reload registry

- name: restart registry if needed
  meta: flush_handlers

...
