---

- name: restart registry
  become: true
  service:
    name: registry
    state: restarted

- name: reload registry
  become: true
  service:
    name: registry
    state: reloaded

- name: validate config
  command: /bin/true

- name: daemon-reload
  become: true
  systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
